### ISSUE TITLE
Add missing datasets not hosted at CSA

### ISSUE THREAD

**Issue by low-decarie** [asc-csa/ckanext-asc-csa#52] opened 2020-11-04 15:17 UTC
Add datasets funded by CSA but not hosted at CSA

**Comment by J-bytes** [comment] 2020-11-07 19:03
Let's not forget about the three missing datasets from the government of canada ckan instance. I sadly am not sure which one exactly is missing but due to problems out of our control, the harvester could not get them.

**Comment by nfee006** [comment] 2021-02-05 19:35
NB J-Bytes comment is addressed in https://github.com/asc-csa/ckanext-asc-csa/issues/53.

**Comment by nfee006** [comment] 2021-08-10 16:48
The open government team has confirmed that the dataset registry is complete at this time. This will, however, be something to keep in mind long-term. We will reopen the issue if need be.

**Closed by nfee006** 2021-08-10 16:48 UTC
Labels: Dataset curation, long-term
