### ISSUE TITLE
500 Server error in CKAN 2.9

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#122] opened 2021-05-28 14:19 UTC
![image](https://user-images.githubusercontent.com/11013061/119997717-05eba780-bf9e-11eb-921b-1dde0b00e79e.png)

Displays instead of API page as well as in place of 404 pages. 

Trying to determine if it's related to https://github.com/ckan/ckan/issues/4791 

FYI, @coleweusthem

**Comment by coleweusthem** [comment] 2021-05-28 14:39
whats the url to get that? I don't have much in the way of documentation for the API or what it does

**Comment by nfee006** [comment] 2021-05-28 14:43
It's just this: http://127.0.0.1:5000/en/API
![image](https://user-images.githubusercontent.com/11013061/120000927-4ef12b00-bfa1-11eb-85cd-2dbd8609145a.png)
Should look like this 

![image](https://user-images.githubusercontent.com/11013061/120001202-8a8bf500-bfa1-11eb-9912-ccbe6583d1df.png)

It's just the vanilla CKAN API though, we haven't changed anything. https://docs.ckan.org/en/2.9/api/

**Comment by nfee006** [comment] 2021-05-28 17:15
Update: also occurs when trying to create a new dataset manually. 

When clicking on this button on the dataset creation page 
![image](https://user-images.githubusercontent.com/11013061/120019668-bb2a5980-bfb6-11eb-89ef-e066b1283171.png)

**Comment by nfee006** [comment] 2021-05-28 17:53
Broken pages: 
- [ ] API - http://127.0.0.1:5000/en/API
- [ ] Add dataset - http://127.0.0.1:5000/en/dataset/new 
- [ ] Add resource - when you click "submit" on this page (example) http://127.0.0.1:5000/en/dataset/testmg/resource/new 
- [ ] Data explorer page - (example) http://127.0.0.1:5000/en/dataset/35103995-4m2o-7a0i-964fusc106cj97/resource/0efe8d2f-6d59-491e-b68c-43265205ba60

**Comment by coleweusthem** [comment] 2021-05-28 17:56
@nfee006, I think they all stem from the same issue. Seems like something from the CSA themeing it breaking something, if I remove both plugins the error pages work. Still trying to isolate where the problem is coming from as the errors aren't really helping narrow it down.

**Comment by nfee006** [comment] 2021-05-28 18:10
Doing the same thing on my side, haven't found a solution yet. 

Highly recommend setting debug = true in ckan.ini and then running pip install -r /usr/lib/ckan/default/src/ckan/dev-requirements.txt in you venv.

**Comment by coleweusthem** [comment] 2021-05-28 18:13
that error actually looks useful. I'll look into that one. Let me know if you figure out the 404 issue.

**Comment by coleweusthem** [comment] 2021-05-28 18:25
@nfee006, could you give me an example of how I get to the "data explorer" and get that error you found?

**Comment by nfee006** [comment] 2021-05-28 18:28
Data explorer page - (example) http://127.0.0.1:5000/en/dataset/35103995-4m2o-7a0i-964fusc106cj97/resource/0efe8d2f-6d59-491e-b68c-43265205ba60

It isn't enabled for every dataset though. Generally look for a csv resource - Go Canada is a good one. 
![image](https://user-images.githubusercontent.com/11013061/120027011-da2de900-bfc0-11eb-8b9c-7a1e9bf6145f.png)

I'm around if you want to have a quick meeting to screenshare etc..

**Comment by coleweusthem** [comment] 2021-05-28 18:29
@nfee006, Thanks, that's what I was looking for. I'll let you know when I push a change

**Comment by nfee006** [comment] 2021-05-28 18:30
> Broken pages:
> 
> * [ ]  API - http://127.0.0.1:5000/en/API
> * [ ]  Add dataset - http://127.0.0.1:5000/en/dataset/new
> * [ ]  Add resource - when you click "submit" on this page (example) http://127.0.0.1:5000/en/dataset/testmg/resource/new
> * [ ]  Data explorer page - (example) http://127.0.0.1:5000/en/dataset/35103995-4m2o-7a0i-964fusc106cj97/resource/0efe8d2f-6d59-491e-b68c-43265205ba60

just in case you missed this one in the flurry of comments. Doesn't seem to be the same issue on every page

**Comment by coleweusthem** [comment] 2021-05-28 18:53
<img width="1226" alt="Screen Shot 2021-05-28 at 3 52 58 PM" src="https://user-images.githubusercontent.com/46227765/120029668-c8524300-bfcc-11eb-93d2-f0c6aed4c89f.png">
Do you know if the data explorer itself is working for this resource?

**Comment by nfee006** [comment] 2021-05-28 19:03
The fact that you even got to that page is great. 

It would need to be in the datastore -ie. but - I assume you're working off network? if I were you, I'd take one of the test datasets and replace the resource URL with something freely available on the web (you could try https://open.canada.ca/data/dataset/dd18f931-a23e-4126-874f-68e1bc73851b/resource/21800371-03f9-434c-8c7b-6039d45a25bf/download/open-science-csa-publications-2017.csv). That way it can use the resource_proxy.

We'll need to test it for the datastore at some point though. You'll need to make sure that datapusher is running when you update the resource and that it's pointing to a single csv (and not a folder). If that doesn't work, you can go to  CKAN_SITE/dataset/DATASET_ID/resource_data/RESOURCE_ID and manually push it to the datastore (click on "edit resource" and then replace "edit" with "data" in the URL).

**Comment by coleweusthem** [comment] 2021-05-28 19:42
for the add dataset page, is it the page or the submission casing the issue? Mines loading fine and I don't think I've done anything.

**Comment by nfee006** [comment] 2021-05-28 19:43
It's the submission

**Comment by nfee006** [comment] 2021-06-02 19:24
Same pkg_dict issue appearing when I use the search page "order by" tool 

![image](https://user-images.githubusercontent.com/11013061/120540362-9a974080-c3b6-11eb-930d-ff6cbad8d859.png)

**Comment by coleweusthem** [comment] 2021-06-02 19:25
another piece to the puzzle. Thanks @nfee006, that might help narrow it down

**Comment by nfee006** [comment] 2021-06-07 19:46
FYI @coleweusthem 

The 404 issue does seem to be resolved with your recent edits - great work!

FYI though, I'm now getting this error when I create a new dataset (same as https://github.com/asc-csa/ckanext-asc-csa/issues/122#issuecomment-850558106)

![image](https://user-images.githubusercontent.com/11013061/121078936-8634b880-c7a7-11eb-802c-0de31a51aa51.png)

**Comment by coleweusthem** [comment] 2021-06-07 19:48
@nfee006, hmmmm, alright maybe I fixed it wrong haha. let me look into it.

**Comment by nfee006** [comment] 2021-06-07 19:57
Should've probably has given you this as well: 

![image](https://user-images.githubusercontent.com/11013061/121080143-0c053380-c7a9-11eb-8080-072f2e824328.png)
 
From the same traceback as my last comment

**Comment by nfee006** [comment] 2021-06-09 13:56
Dataset and resource creation pages now work

**Comment by coleweusthem** [comment] 2021-06-09 13:58
I'm working on sorting atm, it's strange that the search field works but the sorting doesn't, they seem to be connected functionality

**Comment by nfee006** [comment] 2021-06-09 13:59
Spoke a bit too soon for the resource creation page. It works as long as you don't put a URL that it needs to try to push to the datastore. Example https://open.canada.ca/data/dataset/f781b1ff-1205-4e94-93c8-dbb3b8e5973c/resource/f2c7ba28-ed9a-4feb-9bab-9168ccd0e153/download/presentation-csv.csv

![image](https://user-images.githubusercontent.com/11013061/121368787-543b6780-c909-11eb-9242-8396a86da534.png)

**Comment by coleweusthem** [comment] 2021-06-09 14:00
alright, I plan on tackling that next

**Comment by nfee006** [comment] 2021-06-09 14:07
Aaand the dataset creation page error is back intermittently. Does it work on your side? 

When you click on this button 

![image](https://user-images.githubusercontent.com/11013061/121370187-80a3b380-c90a-11eb-873a-956f53248912.png)

![image](https://user-images.githubusercontent.com/11013061/121370066-679b0280-c90a-11eb-9d7e-3f17c46cb101.png)
 
![image](https://user-images.githubusercontent.com/11013061/121370110-708bd400-c90a-11eb-9941-f60c44451710.png)

**Comment by coleweusthem** [comment] 2021-06-09 14:10
@nfee006, that is very strange. it's just when clicking on the add? not the actual action of submitting a resource? Like for some reason the view sometimes breaks? Do you know what you were doing before you tried? maybe something is breaking the context/session variables

**Comment by nfee006** [comment] 2021-06-09 14:12
Just when I'm clicking on the add in that instance. All I had done before that was create a new dataset. Works the first time, less so the second as far as I can tell.

**Comment by coleweusthem** [comment] 2021-06-09 14:21
@nfee006, sorting should work now, but it uses a url parameter instead of a post. If there wasn't a reason for it using a post previously I'll move onto working on the above issues.

**Comment by nfee006** [comment] 2021-06-09 14:25
@coleweusthem I have no issues with that solution as long as it works (seems to) and meets web standards

**Comment by coleweusthem** [comment] 2021-06-09 16:42
@nfee006, I think I've fixed the issue, the problem was coming from the breadcrumb, but we're not actually using the breadcrumb from CKAN so I removed it from the template.

**Comment by coleweusthem** [comment] 2021-06-09 16:43
@nfee006, going to start looking at that datastore issue

**Comment by nfee006** [comment] 2021-06-09 16:47
> @nfee006, I think I've fixed the issue, the problem was coming from the breadcrumb, but we're not actually using the breadcrumb from CKAN so I removed it from the template.

Great - once you push it I'll check it on my side too.

**Comment by coleweusthem** [comment] 2021-06-09 16:47
@nfee006, just pushed

**Comment by nfee006** [comment] 2021-06-09 16:56
> > @nfee006, I think I've fixed the issue, the problem was coming from the breadcrumb, but we're not actually using the breadcrumb from CKAN so I removed it from the template.
> 
> Great - once you push it I'll check it on my side too.

Seems ok on my side! I'll keep an eye on it though.

**Comment by coleweusthem** [comment] 2021-06-10 19:35
@nfee006, I just pushed a fix for that

**Comment by nfee006** [comment] 2021-06-10 19:58
I'm now getting this when I update the URL for a resource 
![image](https://user-images.githubusercontent.com/11013061/121588887-6f3ed200-ca04-11eb-86c4-ebbb246308cb.png)
![image](https://user-images.githubusercontent.com/11013061/121588912-7665e000-ca04-11eb-9a83-3b24990c0d42.png)

However, if I go back, refresh the page, and resubmit it works. Not ideal - any idea where that could be coming from? 

Otherwise your fix seems to have done the trick. Were you able to do much testing on your side as well?

**Comment by coleweusthem** [comment] 2021-06-10 19:58
weird. I'll look into it, haven't seen that one yet

**Comment by coleweusthem** [comment] 2021-06-11 13:18
@nfee006, what are the exact steps you took to get the above error? when I go to a resources edit page, change the url, and press "update resource" it works and doesn't give that error.

**Comment by coleweusthem** [comment] 2021-06-11 16:06
2 separate ones didn't seem to do it. I'm currently working on a new installation guide. I think this was the only with left if I'm not mistaken, If you can figure out how to replicate it let me know and I'll take another look.

**Comment by nfee006** [comment] 2021-06-11 16:59
I'll keep looking around for bugs. I assume that you haven't found any others while testing on your side? If yes, let me know and I can try to replicate if that helps. 

There is still the issue of conformity - can you certify that this meets it (WCAG etc.. same as with the micro apps)? We were conform with CKAN 2.8 but we need to be sure that all of those conformity edits were transferred correctly to 2.9. 

On that note - I saw that you have a commit for accessible pagination https://github.com/asc-csa/ckanext-asc-csa/commit/37b7cc61eb8d71d18a2a305c221a01596bf602c4 (for https://github.com/asc-csa/ckanext-asc-csa/issues/124). Do I need to do anything special to enable it? It doesn't seem to have the aria-labels etc.. on my side. See https://github.com/asc-csa/ckanext-asc-csa/issues?q=is%3Aissue+pagination+is%3Aclosed 

![image](https://user-images.githubusercontent.com/11013061/121723580-ae2c6080-cab4-11eb-962e-013aa4a1a549.png)
 
Also, do we have everything relevant from here? https://github.com/asc-csa/ckanext-asc-csa/issues/90

**Comment by coleweusthem** [comment] 2021-06-11 17:02
@nfee006, sorry forgot to explain it. Similar to how the helpers.py needed to be replaced. Same directory as before, but now you need to replace the pagination.py file instead.

**Closed** 2021-08-10 16:45 UTC
Labels: bug, CKAN 2.9
